/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as WebLiteRouteImport } from './routes/web/lite'
import { Route as AccountsEmailsignupRouteImport } from './routes/accounts/emailsignup'
import { Route as AppTestRouteImport } from './routes/_app/test'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppProfile_nameRouteImport } from './routes/_app/$profile_name'
import { Route as ExploreLocationsIndexRouteImport } from './routes/explore/locations/index'
import { Route as AppProfile_nameIndexRouteImport } from './routes/_app/$profile_name/index'
import { Route as StoriesProfile_nameStory_idRouteImport } from './routes/stories/$profile_name/$story_id'
import { Route as AccountsPasswordResetRouteImport } from './routes/accounts/password/reset'
import { Route as AppPPost_idRouteImport } from './routes/_app/p/$post_id'
import { Route as AppProfile_nameSavedRouteImport } from './routes/_app/$profile_name/saved'
import { Route as AppProfile_nameAlbumsRouteImport } from './routes/_app/$profile_name/albums'
import { Route as ExploreLocationsCountryCodeCountryNameRouteImport } from './routes/explore/locations/$countryCode/$countryName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WebLiteRoute = WebLiteRouteImport.update({
  id: '/web/lite',
  path: '/web/lite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsEmailsignupRoute = AccountsEmailsignupRouteImport.update({
  id: '/accounts/emailsignup',
  path: '/accounts/emailsignup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestRoute = AppTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppProfile_nameRoute = AppProfile_nameRouteImport.update({
  id: '/$profile_name',
  path: '/$profile_name',
  getParentRoute: () => AppRoute,
} as any)
const ExploreLocationsIndexRoute = ExploreLocationsIndexRouteImport.update({
  id: '/explore/locations/',
  path: '/explore/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfile_nameIndexRoute = AppProfile_nameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProfile_nameRoute,
} as any)
const StoriesProfile_nameStory_idRoute =
  StoriesProfile_nameStory_idRouteImport.update({
    id: '/stories/$profile_name/$story_id',
    path: '/stories/$profile_name/$story_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsPasswordResetRoute = AccountsPasswordResetRouteImport.update({
  id: '/accounts/password/reset',
  path: '/accounts/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPPost_idRoute = AppPPost_idRouteImport.update({
  id: '/p/$post_id',
  path: '/p/$post_id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfile_nameSavedRoute = AppProfile_nameSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppProfile_nameRoute,
} as any)
const AppProfile_nameAlbumsRoute = AppProfile_nameAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppProfile_nameRoute,
} as any)
const ExploreLocationsCountryCodeCountryNameRoute =
  ExploreLocationsCountryCodeCountryNameRouteImport.update({
    id: '/explore/locations/$countryCode/$countryName',
    path: '/explore/locations/$countryCode/$countryName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$profile_name': typeof AppProfile_nameRouteWithChildren
  '/explore': typeof AppExploreRoute
  '/test': typeof AppTestRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupRoute
  '/web/lite': typeof WebLiteRoute
  '/': typeof AppIndexRoute
  '/$profile_name/albums': typeof AppProfile_nameAlbumsRoute
  '/$profile_name/saved': typeof AppProfile_nameSavedRoute
  '/p/$post_id': typeof AppPPost_idRoute
  '/accounts/password/reset': typeof AccountsPasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
  '/$profile_name/': typeof AppProfile_nameIndexRoute
  '/explore/locations': typeof ExploreLocationsIndexRoute
  '/explore/locations/$countryCode/$countryName': typeof ExploreLocationsCountryCodeCountryNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/explore': typeof AppExploreRoute
  '/test': typeof AppTestRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupRoute
  '/web/lite': typeof WebLiteRoute
  '/': typeof AppIndexRoute
  '/$profile_name/albums': typeof AppProfile_nameAlbumsRoute
  '/$profile_name/saved': typeof AppProfile_nameSavedRoute
  '/p/$post_id': typeof AppPPost_idRoute
  '/accounts/password/reset': typeof AccountsPasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
  '/$profile_name': typeof AppProfile_nameIndexRoute
  '/explore/locations': typeof ExploreLocationsIndexRoute
  '/explore/locations/$countryCode/$countryName': typeof ExploreLocationsCountryCodeCountryNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$profile_name': typeof AppProfile_nameRouteWithChildren
  '/_app/explore': typeof AppExploreRoute
  '/_app/test': typeof AppTestRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupRoute
  '/web/lite': typeof WebLiteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$profile_name/albums': typeof AppProfile_nameAlbumsRoute
  '/_app/$profile_name/saved': typeof AppProfile_nameSavedRoute
  '/_app/p/$post_id': typeof AppPPost_idRoute
  '/accounts/password/reset': typeof AccountsPasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
  '/_app/$profile_name/': typeof AppProfile_nameIndexRoute
  '/explore/locations/': typeof ExploreLocationsIndexRoute
  '/explore/locations/$countryCode/$countryName': typeof ExploreLocationsCountryCodeCountryNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$profile_name'
    | '/explore'
    | '/test'
    | '/accounts/emailsignup'
    | '/web/lite'
    | '/'
    | '/$profile_name/albums'
    | '/$profile_name/saved'
    | '/p/$post_id'
    | '/accounts/password/reset'
    | '/stories/$profile_name/$story_id'
    | '/$profile_name/'
    | '/explore/locations'
    | '/explore/locations/$countryCode/$countryName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/explore'
    | '/test'
    | '/accounts/emailsignup'
    | '/web/lite'
    | '/'
    | '/$profile_name/albums'
    | '/$profile_name/saved'
    | '/p/$post_id'
    | '/accounts/password/reset'
    | '/stories/$profile_name/$story_id'
    | '/$profile_name'
    | '/explore/locations'
    | '/explore/locations/$countryCode/$countryName'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$profile_name'
    | '/_app/explore'
    | '/_app/test'
    | '/accounts/emailsignup'
    | '/web/lite'
    | '/_app/'
    | '/_app/$profile_name/albums'
    | '/_app/$profile_name/saved'
    | '/_app/p/$post_id'
    | '/accounts/password/reset'
    | '/stories/$profile_name/$story_id'
    | '/_app/$profile_name/'
    | '/explore/locations/'
    | '/explore/locations/$countryCode/$countryName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AccountsEmailsignupRoute: typeof AccountsEmailsignupRoute
  WebLiteRoute: typeof WebLiteRoute
  AccountsPasswordResetRoute: typeof AccountsPasswordResetRoute
  StoriesProfile_nameStory_idRoute: typeof StoriesProfile_nameStory_idRoute
  ExploreLocationsIndexRoute: typeof ExploreLocationsIndexRoute
  ExploreLocationsCountryCodeCountryNameRoute: typeof ExploreLocationsCountryCodeCountryNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/web/lite': {
      id: '/web/lite'
      path: '/web/lite'
      fullPath: '/web/lite'
      preLoaderRoute: typeof WebLiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup': {
      id: '/accounts/emailsignup'
      path: '/accounts/emailsignup'
      fullPath: '/accounts/emailsignup'
      preLoaderRoute: typeof AccountsEmailsignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/test': {
      id: '/_app/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$profile_name': {
      id: '/_app/$profile_name'
      path: '/$profile_name'
      fullPath: '/$profile_name'
      preLoaderRoute: typeof AppProfile_nameRouteImport
      parentRoute: typeof AppRoute
    }
    '/explore/locations/': {
      id: '/explore/locations/'
      path: '/explore/locations'
      fullPath: '/explore/locations'
      preLoaderRoute: typeof ExploreLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$profile_name/': {
      id: '/_app/$profile_name/'
      path: '/'
      fullPath: '/$profile_name/'
      preLoaderRoute: typeof AppProfile_nameIndexRouteImport
      parentRoute: typeof AppProfile_nameRoute
    }
    '/stories/$profile_name/$story_id': {
      id: '/stories/$profile_name/$story_id'
      path: '/stories/$profile_name/$story_id'
      fullPath: '/stories/$profile_name/$story_id'
      preLoaderRoute: typeof StoriesProfile_nameStory_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/password/reset': {
      id: '/accounts/password/reset'
      path: '/accounts/password/reset'
      fullPath: '/accounts/password/reset'
      preLoaderRoute: typeof AccountsPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$post_id': {
      id: '/_app/p/$post_id'
      path: '/p/$post_id'
      fullPath: '/p/$post_id'
      preLoaderRoute: typeof AppPPost_idRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$profile_name/saved': {
      id: '/_app/$profile_name/saved'
      path: '/saved'
      fullPath: '/$profile_name/saved'
      preLoaderRoute: typeof AppProfile_nameSavedRouteImport
      parentRoute: typeof AppProfile_nameRoute
    }
    '/_app/$profile_name/albums': {
      id: '/_app/$profile_name/albums'
      path: '/albums'
      fullPath: '/$profile_name/albums'
      preLoaderRoute: typeof AppProfile_nameAlbumsRouteImport
      parentRoute: typeof AppProfile_nameRoute
    }
    '/explore/locations/$countryCode/$countryName': {
      id: '/explore/locations/$countryCode/$countryName'
      path: '/explore/locations/$countryCode/$countryName'
      fullPath: '/explore/locations/$countryCode/$countryName'
      preLoaderRoute: typeof ExploreLocationsCountryCodeCountryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppProfile_nameRouteChildren {
  AppProfile_nameAlbumsRoute: typeof AppProfile_nameAlbumsRoute
  AppProfile_nameSavedRoute: typeof AppProfile_nameSavedRoute
  AppProfile_nameIndexRoute: typeof AppProfile_nameIndexRoute
}

const AppProfile_nameRouteChildren: AppProfile_nameRouteChildren = {
  AppProfile_nameAlbumsRoute: AppProfile_nameAlbumsRoute,
  AppProfile_nameSavedRoute: AppProfile_nameSavedRoute,
  AppProfile_nameIndexRoute: AppProfile_nameIndexRoute,
}

const AppProfile_nameRouteWithChildren = AppProfile_nameRoute._addFileChildren(
  AppProfile_nameRouteChildren
)

interface AppRouteChildren {
  AppProfile_nameRoute: typeof AppProfile_nameRouteWithChildren
  AppExploreRoute: typeof AppExploreRoute
  AppTestRoute: typeof AppTestRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPPost_idRoute: typeof AppPPost_idRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfile_nameRoute: AppProfile_nameRouteWithChildren,
  AppExploreRoute: AppExploreRoute,
  AppTestRoute: AppTestRoute,
  AppIndexRoute: AppIndexRoute,
  AppPPost_idRoute: AppPPost_idRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AccountsEmailsignupRoute: AccountsEmailsignupRoute,
  WebLiteRoute: WebLiteRoute,
  AccountsPasswordResetRoute: AccountsPasswordResetRoute,
  StoriesProfile_nameStory_idRoute: StoriesProfile_nameStory_idRoute,
  ExploreLocationsIndexRoute: ExploreLocationsIndexRoute,
  ExploreLocationsCountryCodeCountryNameRoute:
    ExploreLocationsCountryCodeCountryNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
