/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as WebLiteRouteImport } from './routes/web/lite'
import { Route as StoriesUser_idRouteImport } from './routes/stories/$user_id'
import { Route as AppTestRouteImport } from './routes/_app/test'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppUserIdRouteImport } from './routes/_app/$userId'
import { Route as ExploreLocationsIndexRouteImport } from './routes/explore/locations/index'
import { Route as AccountsEmailsignupIndexRouteImport } from './routes/accounts/emailsignup/index'
import { Route as AppUserIdIndexRouteImport } from './routes/_app/$userId/index'
import { Route as StoriesProfile_nameStory_idRouteImport } from './routes/stories/$profile_name/$story_id'
import { Route as AccountsPasswordResetRouteImport } from './routes/accounts/password/reset'
import { Route as AccountsEmailsignupVerificationRouteImport } from './routes/accounts/emailsignup/verification'
import { Route as AccountsEmailsignupEmailChangeRouteImport } from './routes/accounts/emailsignup/email-change'
import { Route as AccountsEmailsignupCaptchaRouteImport } from './routes/accounts/emailsignup/captcha'
import { Route as AccountsEmailsignupBirthdayRouteImport } from './routes/accounts/emailsignup/birthday'
import { Route as AppPPost_idRouteImport } from './routes/_app/p/$post_id'
import { Route as AppUserIdSavedRouteImport } from './routes/_app/$userId/saved'
import { Route as AppUserIdAlbumsRouteImport } from './routes/_app/$userId/albums'
import { Route as ExploreLocationsCountryCodeCountryNameRouteImport } from './routes/explore/locations/$countryCode/$countryName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const WebLiteRoute = WebLiteRouteImport.update({
  id: '/web/lite',
  path: '/web/lite',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesUser_idRoute = StoriesUser_idRouteImport.update({
  id: '/stories/$user_id',
  path: '/stories/$user_id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTestRoute = AppTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppUserIdRoute = AppUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppRoute,
} as any)
const ExploreLocationsIndexRoute = ExploreLocationsIndexRouteImport.update({
  id: '/explore/locations/',
  path: '/explore/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsEmailsignupIndexRoute =
  AccountsEmailsignupIndexRouteImport.update({
    id: '/accounts/emailsignup/',
    path: '/accounts/emailsignup/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppUserIdIndexRoute = AppUserIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUserIdRoute,
} as any)
const StoriesProfile_nameStory_idRoute =
  StoriesProfile_nameStory_idRouteImport.update({
    id: '/stories/$profile_name/$story_id',
    path: '/stories/$profile_name/$story_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsPasswordResetRoute = AccountsPasswordResetRouteImport.update({
  id: '/accounts/password/reset',
  path: '/accounts/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsEmailsignupVerificationRoute =
  AccountsEmailsignupVerificationRouteImport.update({
    id: '/accounts/emailsignup/verification',
    path: '/accounts/emailsignup/verification',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsEmailsignupEmailChangeRoute =
  AccountsEmailsignupEmailChangeRouteImport.update({
    id: '/accounts/emailsignup/email-change',
    path: '/accounts/emailsignup/email-change',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsEmailsignupCaptchaRoute =
  AccountsEmailsignupCaptchaRouteImport.update({
    id: '/accounts/emailsignup/captcha',
    path: '/accounts/emailsignup/captcha',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsEmailsignupBirthdayRoute =
  AccountsEmailsignupBirthdayRouteImport.update({
    id: '/accounts/emailsignup/birthday',
    path: '/accounts/emailsignup/birthday',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppPPost_idRoute = AppPPost_idRouteImport.update({
  id: '/p/$post_id',
  path: '/p/$post_id',
  getParentRoute: () => AppRoute,
} as any)
const AppUserIdSavedRoute = AppUserIdSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppUserIdRoute,
} as any)
const AppUserIdAlbumsRoute = AppUserIdAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppUserIdRoute,
} as any)
const ExploreLocationsCountryCodeCountryNameRoute =
  ExploreLocationsCountryCodeCountryNameRouteImport.update({
    id: '/explore/locations/$countryCode/$countryName',
    path: '/explore/locations/$countryCode/$countryName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/$userId': typeof AppUserIdRouteWithChildren
  '/explore': typeof AppExploreRoute
  '/test': typeof AppTestRoute
  '/stories/$user_id': typeof StoriesUser_idRoute
  '/web/lite': typeof WebLiteRoute
  '/': typeof AppIndexRoute
  '/$userId/albums': typeof AppUserIdAlbumsRoute
  '/$userId/saved': typeof AppUserIdSavedRoute
  '/p/$post_id': typeof AppPPost_idRoute
  '/accounts/emailsignup/birthday': typeof AccountsEmailsignupBirthdayRoute
  '/accounts/emailsignup/captcha': typeof AccountsEmailsignupCaptchaRoute
  '/accounts/emailsignup/email-change': typeof AccountsEmailsignupEmailChangeRoute
  '/accounts/emailsignup/verification': typeof AccountsEmailsignupVerificationRoute
  '/accounts/password/reset': typeof AccountsPasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
  '/$userId/': typeof AppUserIdIndexRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupIndexRoute
  '/explore/locations': typeof ExploreLocationsIndexRoute
  '/explore/locations/$countryCode/$countryName': typeof ExploreLocationsCountryCodeCountryNameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/explore': typeof AppExploreRoute
  '/test': typeof AppTestRoute
  '/stories/$user_id': typeof StoriesUser_idRoute
  '/web/lite': typeof WebLiteRoute
  '/': typeof AppIndexRoute
  '/$userId/albums': typeof AppUserIdAlbumsRoute
  '/$userId/saved': typeof AppUserIdSavedRoute
  '/p/$post_id': typeof AppPPost_idRoute
  '/accounts/emailsignup/birthday': typeof AccountsEmailsignupBirthdayRoute
  '/accounts/emailsignup/captcha': typeof AccountsEmailsignupCaptchaRoute
  '/accounts/emailsignup/email-change': typeof AccountsEmailsignupEmailChangeRoute
  '/accounts/emailsignup/verification': typeof AccountsEmailsignupVerificationRoute
  '/accounts/password/reset': typeof AccountsPasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
  '/$userId': typeof AppUserIdIndexRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupIndexRoute
  '/explore/locations': typeof ExploreLocationsIndexRoute
  '/explore/locations/$countryCode/$countryName': typeof ExploreLocationsCountryCodeCountryNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$userId': typeof AppUserIdRouteWithChildren
  '/_app/explore': typeof AppExploreRoute
  '/_app/test': typeof AppTestRoute
  '/stories/$user_id': typeof StoriesUser_idRoute
  '/web/lite': typeof WebLiteRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$userId/albums': typeof AppUserIdAlbumsRoute
  '/_app/$userId/saved': typeof AppUserIdSavedRoute
  '/_app/p/$post_id': typeof AppPPost_idRoute
  '/accounts/emailsignup/birthday': typeof AccountsEmailsignupBirthdayRoute
  '/accounts/emailsignup/captcha': typeof AccountsEmailsignupCaptchaRoute
  '/accounts/emailsignup/email-change': typeof AccountsEmailsignupEmailChangeRoute
  '/accounts/emailsignup/verification': typeof AccountsEmailsignupVerificationRoute
  '/accounts/password/reset': typeof AccountsPasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
  '/_app/$userId/': typeof AppUserIdIndexRoute
  '/accounts/emailsignup/': typeof AccountsEmailsignupIndexRoute
  '/explore/locations/': typeof ExploreLocationsIndexRoute
  '/explore/locations/$countryCode/$countryName': typeof ExploreLocationsCountryCodeCountryNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/$userId'
    | '/explore'
    | '/test'
    | '/stories/$user_id'
    | '/web/lite'
    | '/'
    | '/$userId/albums'
    | '/$userId/saved'
    | '/p/$post_id'
    | '/accounts/emailsignup/birthday'
    | '/accounts/emailsignup/captcha'
    | '/accounts/emailsignup/email-change'
    | '/accounts/emailsignup/verification'
    | '/accounts/password/reset'
    | '/stories/$profile_name/$story_id'
    | '/$userId/'
    | '/accounts/emailsignup'
    | '/explore/locations'
    | '/explore/locations/$countryCode/$countryName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/explore'
    | '/test'
    | '/stories/$user_id'
    | '/web/lite'
    | '/'
    | '/$userId/albums'
    | '/$userId/saved'
    | '/p/$post_id'
    | '/accounts/emailsignup/birthday'
    | '/accounts/emailsignup/captcha'
    | '/accounts/emailsignup/email-change'
    | '/accounts/emailsignup/verification'
    | '/accounts/password/reset'
    | '/stories/$profile_name/$story_id'
    | '/$userId'
    | '/accounts/emailsignup'
    | '/explore/locations'
    | '/explore/locations/$countryCode/$countryName'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$userId'
    | '/_app/explore'
    | '/_app/test'
    | '/stories/$user_id'
    | '/web/lite'
    | '/_app/'
    | '/_app/$userId/albums'
    | '/_app/$userId/saved'
    | '/_app/p/$post_id'
    | '/accounts/emailsignup/birthday'
    | '/accounts/emailsignup/captcha'
    | '/accounts/emailsignup/email-change'
    | '/accounts/emailsignup/verification'
    | '/accounts/password/reset'
    | '/stories/$profile_name/$story_id'
    | '/_app/$userId/'
    | '/accounts/emailsignup/'
    | '/explore/locations/'
    | '/explore/locations/$countryCode/$countryName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  StoriesUser_idRoute: typeof StoriesUser_idRoute
  WebLiteRoute: typeof WebLiteRoute
  AccountsEmailsignupBirthdayRoute: typeof AccountsEmailsignupBirthdayRoute
  AccountsEmailsignupCaptchaRoute: typeof AccountsEmailsignupCaptchaRoute
  AccountsEmailsignupEmailChangeRoute: typeof AccountsEmailsignupEmailChangeRoute
  AccountsEmailsignupVerificationRoute: typeof AccountsEmailsignupVerificationRoute
  AccountsPasswordResetRoute: typeof AccountsPasswordResetRoute
  StoriesProfile_nameStory_idRoute: typeof StoriesProfile_nameStory_idRoute
  AccountsEmailsignupIndexRoute: typeof AccountsEmailsignupIndexRoute
  ExploreLocationsIndexRoute: typeof ExploreLocationsIndexRoute
  ExploreLocationsCountryCodeCountryNameRoute: typeof ExploreLocationsCountryCodeCountryNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/web/lite': {
      id: '/web/lite'
      path: '/web/lite'
      fullPath: '/web/lite'
      preLoaderRoute: typeof WebLiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$user_id': {
      id: '/stories/$user_id'
      path: '/stories/$user_id'
      fullPath: '/stories/$user_id'
      preLoaderRoute: typeof StoriesUser_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/test': {
      id: '/_app/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AppTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$userId': {
      id: '/_app/$userId'
      path: '/$userId'
      fullPath: '/$userId'
      preLoaderRoute: typeof AppUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/explore/locations/': {
      id: '/explore/locations/'
      path: '/explore/locations'
      fullPath: '/explore/locations'
      preLoaderRoute: typeof ExploreLocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup/': {
      id: '/accounts/emailsignup/'
      path: '/accounts/emailsignup'
      fullPath: '/accounts/emailsignup'
      preLoaderRoute: typeof AccountsEmailsignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$userId/': {
      id: '/_app/$userId/'
      path: '/'
      fullPath: '/$userId/'
      preLoaderRoute: typeof AppUserIdIndexRouteImport
      parentRoute: typeof AppUserIdRoute
    }
    '/stories/$profile_name/$story_id': {
      id: '/stories/$profile_name/$story_id'
      path: '/stories/$profile_name/$story_id'
      fullPath: '/stories/$profile_name/$story_id'
      preLoaderRoute: typeof StoriesProfile_nameStory_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/password/reset': {
      id: '/accounts/password/reset'
      path: '/accounts/password/reset'
      fullPath: '/accounts/password/reset'
      preLoaderRoute: typeof AccountsPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup/verification': {
      id: '/accounts/emailsignup/verification'
      path: '/accounts/emailsignup/verification'
      fullPath: '/accounts/emailsignup/verification'
      preLoaderRoute: typeof AccountsEmailsignupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup/email-change': {
      id: '/accounts/emailsignup/email-change'
      path: '/accounts/emailsignup/email-change'
      fullPath: '/accounts/emailsignup/email-change'
      preLoaderRoute: typeof AccountsEmailsignupEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup/captcha': {
      id: '/accounts/emailsignup/captcha'
      path: '/accounts/emailsignup/captcha'
      fullPath: '/accounts/emailsignup/captcha'
      preLoaderRoute: typeof AccountsEmailsignupCaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup/birthday': {
      id: '/accounts/emailsignup/birthday'
      path: '/accounts/emailsignup/birthday'
      fullPath: '/accounts/emailsignup/birthday'
      preLoaderRoute: typeof AccountsEmailsignupBirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/p/$post_id': {
      id: '/_app/p/$post_id'
      path: '/p/$post_id'
      fullPath: '/p/$post_id'
      preLoaderRoute: typeof AppPPost_idRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$userId/saved': {
      id: '/_app/$userId/saved'
      path: '/saved'
      fullPath: '/$userId/saved'
      preLoaderRoute: typeof AppUserIdSavedRouteImport
      parentRoute: typeof AppUserIdRoute
    }
    '/_app/$userId/albums': {
      id: '/_app/$userId/albums'
      path: '/albums'
      fullPath: '/$userId/albums'
      preLoaderRoute: typeof AppUserIdAlbumsRouteImport
      parentRoute: typeof AppUserIdRoute
    }
    '/explore/locations/$countryCode/$countryName': {
      id: '/explore/locations/$countryCode/$countryName'
      path: '/explore/locations/$countryCode/$countryName'
      fullPath: '/explore/locations/$countryCode/$countryName'
      preLoaderRoute: typeof ExploreLocationsCountryCodeCountryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppUserIdRouteChildren {
  AppUserIdAlbumsRoute: typeof AppUserIdAlbumsRoute
  AppUserIdSavedRoute: typeof AppUserIdSavedRoute
  AppUserIdIndexRoute: typeof AppUserIdIndexRoute
}

const AppUserIdRouteChildren: AppUserIdRouteChildren = {
  AppUserIdAlbumsRoute: AppUserIdAlbumsRoute,
  AppUserIdSavedRoute: AppUserIdSavedRoute,
  AppUserIdIndexRoute: AppUserIdIndexRoute,
}

const AppUserIdRouteWithChildren = AppUserIdRoute._addFileChildren(
  AppUserIdRouteChildren
)

interface AppRouteChildren {
  AppUserIdRoute: typeof AppUserIdRouteWithChildren
  AppExploreRoute: typeof AppExploreRoute
  AppTestRoute: typeof AppTestRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPPost_idRoute: typeof AppPPost_idRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppUserIdRoute: AppUserIdRouteWithChildren,
  AppExploreRoute: AppExploreRoute,
  AppTestRoute: AppTestRoute,
  AppIndexRoute: AppIndexRoute,
  AppPPost_idRoute: AppPPost_idRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  StoriesUser_idRoute: StoriesUser_idRoute,
  WebLiteRoute: WebLiteRoute,
  AccountsEmailsignupBirthdayRoute: AccountsEmailsignupBirthdayRoute,
  AccountsEmailsignupCaptchaRoute: AccountsEmailsignupCaptchaRoute,
  AccountsEmailsignupEmailChangeRoute: AccountsEmailsignupEmailChangeRoute,
  AccountsEmailsignupVerificationRoute: AccountsEmailsignupVerificationRoute,
  AccountsPasswordResetRoute: AccountsPasswordResetRoute,
  StoriesProfile_nameStory_idRoute: StoriesProfile_nameStory_idRoute,
  AccountsEmailsignupIndexRoute: AccountsEmailsignupIndexRoute,
  ExploreLocationsIndexRoute: ExploreLocationsIndexRoute,
  ExploreLocationsCountryCodeCountryNameRoute:
    ExploreLocationsCountryCodeCountryNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
