/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as Profile_nameRouteImport } from './routes/$profile_name'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PasswordResetRouteImport } from './routes/password/reset'
import { Route as PProfile_nameRouteImport } from './routes/p/$profile_name'
import { Route as AccountsEmailsignupRouteImport } from './routes/accounts/emailsignup'
import { Route as Profile_nameSavedRouteImport } from './routes/$profile_name/saved'
import { Route as StoriesProfile_nameStory_idRouteImport } from './routes/stories/$profile_name/$story_id'

const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const Profile_nameRoute = Profile_nameRouteImport.update({
  id: '/$profile_name',
  path: '/$profile_name',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PProfile_nameRoute = PProfile_nameRouteImport.update({
  id: '/p/$profile_name',
  path: '/p/$profile_name',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsEmailsignupRoute = AccountsEmailsignupRouteImport.update({
  id: '/accounts/emailsignup',
  path: '/accounts/emailsignup',
  getParentRoute: () => rootRouteImport,
} as any)
const Profile_nameSavedRoute = Profile_nameSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => Profile_nameRoute,
} as any)
const StoriesProfile_nameStory_idRoute =
  StoriesProfile_nameStory_idRouteImport.update({
    id: '/stories/$profile_name/$story_id',
    path: '/stories/$profile_name/$story_id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$profile_name': typeof Profile_nameRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/$profile_name/saved': typeof Profile_nameSavedRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupRoute
  '/p/$profile_name': typeof PProfile_nameRoute
  '/password/reset': typeof PasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$profile_name': typeof Profile_nameRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/$profile_name/saved': typeof Profile_nameSavedRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupRoute
  '/p/$profile_name': typeof PProfile_nameRoute
  '/password/reset': typeof PasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$profile_name': typeof Profile_nameRouteWithChildren
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/$profile_name/saved': typeof Profile_nameSavedRoute
  '/accounts/emailsignup': typeof AccountsEmailsignupRoute
  '/p/$profile_name': typeof PProfile_nameRoute
  '/password/reset': typeof PasswordResetRoute
  '/stories/$profile_name/$story_id': typeof StoriesProfile_nameStory_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$profile_name'
    | '/explore'
    | '/login'
    | '/me'
    | '/$profile_name/saved'
    | '/accounts/emailsignup'
    | '/p/$profile_name'
    | '/password/reset'
    | '/stories/$profile_name/$story_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$profile_name'
    | '/explore'
    | '/login'
    | '/me'
    | '/$profile_name/saved'
    | '/accounts/emailsignup'
    | '/p/$profile_name'
    | '/password/reset'
    | '/stories/$profile_name/$story_id'
  id:
    | '__root__'
    | '/'
    | '/$profile_name'
    | '/explore'
    | '/login'
    | '/me'
    | '/$profile_name/saved'
    | '/accounts/emailsignup'
    | '/p/$profile_name'
    | '/password/reset'
    | '/stories/$profile_name/$story_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Profile_nameRoute: typeof Profile_nameRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  AccountsEmailsignupRoute: typeof AccountsEmailsignupRoute
  PProfile_nameRoute: typeof PProfile_nameRoute
  PasswordResetRoute: typeof PasswordResetRoute
  StoriesProfile_nameStory_idRoute: typeof StoriesProfile_nameStory_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$profile_name': {
      id: '/$profile_name'
      path: '/$profile_name'
      fullPath: '/$profile_name'
      preLoaderRoute: typeof Profile_nameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$profile_name': {
      id: '/p/$profile_name'
      path: '/p/$profile_name'
      fullPath: '/p/$profile_name'
      preLoaderRoute: typeof PProfile_nameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/emailsignup': {
      id: '/accounts/emailsignup'
      path: '/accounts/emailsignup'
      fullPath: '/accounts/emailsignup'
      preLoaderRoute: typeof AccountsEmailsignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$profile_name/saved': {
      id: '/$profile_name/saved'
      path: '/saved'
      fullPath: '/$profile_name/saved'
      preLoaderRoute: typeof Profile_nameSavedRouteImport
      parentRoute: typeof Profile_nameRoute
    }
    '/stories/$profile_name/$story_id': {
      id: '/stories/$profile_name/$story_id'
      path: '/stories/$profile_name/$story_id'
      fullPath: '/stories/$profile_name/$story_id'
      preLoaderRoute: typeof StoriesProfile_nameStory_idRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Profile_nameRouteChildren {
  Profile_nameSavedRoute: typeof Profile_nameSavedRoute
}

const Profile_nameRouteChildren: Profile_nameRouteChildren = {
  Profile_nameSavedRoute: Profile_nameSavedRoute,
}

const Profile_nameRouteWithChildren = Profile_nameRoute._addFileChildren(
  Profile_nameRouteChildren
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Profile_nameRoute: Profile_nameRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  AccountsEmailsignupRoute: AccountsEmailsignupRoute,
  PProfile_nameRoute: PProfile_nameRoute,
  PasswordResetRoute: PasswordResetRoute,
  StoriesProfile_nameStory_idRoute: StoriesProfile_nameStory_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
